name: API Workflow

on: [push]

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use API Token
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Token is available"
          # ឧទាហរណ៍:
          # curl -H "Authorization: Bearer $API_TOKEN" https://api.example.com
